### ISSUE TITLE
TextField design

### ISSUE THREAD

**Issue by sailor95** [sailor95/dh-uikit#1]
## Direction Draft

- Controlled
  - Case: most of the time
- Uncontrolled
  - Case: type='file'
  - Case: only need to get input value without having to re-render onChange

## Props Draft

- value
- defaultValue
- prefix
- suffix
- placeholder
- isDisabled
- isValid (or isError?)
- onChange

**Comment by davehuang-tw** [comment]
Done: b609cc2fd6974657b54ce2791ff44d0132299e70
